#!/usr/bin/env bash
# Script to installs nginx server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
echo 'Hello World!' |sudo tee  /var/www/html/index.html
sudo service nginx start
