#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.7 -y
apt-get update
apt-get install haproxy=2.0.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend
backend web-backend
        balance roundrobin
        server web-01 54.237.78.38:80 check
        server web-02 34.207.64.44:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
